language: 

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: trusty # Ubuntu 14.04.

compiler:
  - gcc

install: sh ./.travis/install-$TRAVIS_OS_NAME-deps.sh

addons:
  apt:
    packages:
      - cmake

matrix:
  include:
    - env:
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - env:
      os: osx

script:
  - echo "hi"

notifications:
  email:
    on_success: never
    on_failure: never

