language: 

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: trusty # Ubuntu 14.04.

matrix:
  include:
    - env: CC=gcc-5; export CXX=g++-5; export FC=gfortran-5
      os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
              key_url: http://apt.llvm.org/llvm-snapshot.gpg.key
            - sourceline: 'ppa:dzombie/ccache'
          packages:
            - ccache
            - gcc-5
            - g++-5
            - gfortran-5
            - libstdc++-5-dev

    - env:
      os: osx

install: 
  - echo `which $CC`
  - echo `which $CXX`
  - echo `which $FC`
  - sh ./.travis/install-$TRAVIS_OS_NAME-deps.sh

script:
  - echo "hi"

notifications:
  email:
    on_success: never
    on_failure: never

