language: 

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: trusty # Ubuntu 14.04.

compiler:
  - gcc

install: sh ./.travis/install-$TRAVIS_OS_NAME-deps.sh

addons:
  apt:
    packages:
      - cmake

matrix:
  include:
    # linux + gcc-5 + DEBUG=0
    #- env: DEBUG=0; CC=gcc-5; export CXX=g++-5; export FC=gfortran-5
    #  os: linux

    - env: CC=gcc-7; export CXX=g++-7; export FC=gfortran-7
      os: osx

script: 
  - echo CC=${CC}
  - echo CXX=${CXX}
  - echo FC=${FC}

notifications:
  email:
    on_success: never
    on_failure: never
